# Generated by Django 3.2.15 on 2023-04-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_driver_mobil1e_no'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joinsdsded',
        ),
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='store.office_location'),
            preserve_default=False,
        ),
    ]
