# Generated by Django 4.1.5 on 2023-04-02 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined1',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
