# Generated by Django 4.1.5 on 2023-04-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_date_joined1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='office_location',
        ),
    ]
