# Generated by Django 4.1.5 on 2023-04-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=120, unique=True)),
                ('driving_licence', models.CharField(max_length=120, unique=True)),
                ('adhar_card', models.CharField(max_length=120, unique=True)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='office_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='petrol_pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='truck_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120, unique=True)),
                ('bank_acc', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('pan_card', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='truck_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=120, unique=True)),
                ('insurance_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('permit_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('puc_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('fitness', models.CharField(blank=True, max_length=120, null=True)),
                ('truck_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.truck_owner')),
            ],
        ),
        migrations.CreateModel(
            name='taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.district')),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.office_location')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeredfed', to='store.office_location')),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefdws', to='store.taluka')),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_rate', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfdfdf', to='store.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfddsdedfdf', to='store.station')),
            ],
        ),
        migrations.CreateModel(
            name='onaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scsdsds', to='store.company')),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sefedsfwfe', to='store.office_location')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='office_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.office_location'),
        ),
        migrations.CreateModel(
            name='consignor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builty_code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket', to='store.company')),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsfwfe', to='store.office_location')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfsf', to='store.company')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds', to='store.consignor')),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fefefe4gefd', to='store.office_location')),
            ],
        ),
    ]
