# Generated by Django 4.1.5 on 2023-04-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=120, unique=True)),
                ('driving_licence', models.CharField(max_length=120, unique=True)),
                ('adhar_card', models.CharField(max_length=120, unique=True)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='office_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='petrol_pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='truck_details',
            name='company',
        ),
        migrations.RemoveField(
            model_name='truck_owner',
            name='truck',
        ),
        migrations.AddField(
            model_name='consignor',
            name='builty_code',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='taluka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fefdws', to='store.taluka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck_details',
            name='truck_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.truck_owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck_owner',
            name='pan_card',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck_details',
            name='fitness',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='truck_details',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck_details',
            name='permit_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck_details',
            name='puc_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck_owner',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='truck_owner',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='truck_owner',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_rate', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfdfdf', to='store.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfddsdedfdf', to='store.station')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fefefe4gefd', to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignor',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsfwfe', to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onaccount',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sefedsfwfe', to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eeredfed', to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taluka',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.office_location'),
            preserve_default=False,
        ),
    ]
