# Generated by Django 4.1.5 on 2023-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_driver_mobil1e_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='builty_code',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
