# Generated by Django 4.1.5 on 2023-03-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_truck_details_fitness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_details',
            name='company',
        ),
    ]
