# Generated by Django 4.1.5 on 2023-03-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_truck_details_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_rate', models.IntegerField()),
                ('own_rate', models.IntegerField()),
                ('from_statation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfdfdf', to='store.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfgfddsdedfdf', to='store.station')),
            ],
        ),
    ]
