# Generated by Django 4.1.5 on 2023-04-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_consignor_builty_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='truck_owner',
            name='bank_acc',
        ),
        migrations.RemoveField(
            model_name='truck_owner',
            name='pan_card',
        ),
        migrations.AlterField(
            model_name='article',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fefefe4gefd', to='store.office_location'),
        ),
        migrations.AlterField(
            model_name='consignor',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsfwfe', to='store.office_location'),
        ),
        migrations.AlterField(
            model_name='onaccount',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sefedsfwfe', to='store.office_location'),
        ),
        migrations.AlterField(
            model_name='station',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeredfed', to='store.office_location'),
        ),
        migrations.AlterField(
            model_name='taluka',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.office_location'),
        ),
    ]
