# Generated by Django 4.1.5 on 2023-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rates',
            new_name='rate',
        ),
    ]
