# Generated by Django 4.1.5 on 2023-04-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_truck_owner_address_truck_owner_bank_acc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='adhar_card',
            new_name='adhar_card1',
        ),
    ]
