# Generated by Django 4.1.5 on 2023-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_from_statation_rate_from_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='petrol_pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
