# Generated by Django 4.1.5 on 2023-04-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_adhar_card1_driver_adhar_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='adhar_card',
            new_name='adhar_card1',
        ),
    ]
