# Generated by Django 4.1.5 on 2023-03-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_drivers_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drivers_details',
            new_name='driver',
        ),
    ]
