# Generated by Django 4.1.5 on 2023-04-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_adhar_card1_driver_adhar_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='from_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('office_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eereefedfeferefefdfed', to='store.office_location')),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xvds', to='store.taluka')),
            ],
        ),
    ]
