# Generated by Django 4.1.5 on 2023-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_drivers_details_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='builty_code',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
