# Generated by Django 4.1.5 on 2023-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_from_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_licence_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
