# Generated by Django 4.1.5 on 2023-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_driver_driving_licence_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_owner',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
