# Generated by Django 4.1.5 on 2024-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_truck_owner_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='from_station',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
