# Generated by Django 4.1.5 on 2023-03-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_truck_owner_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='taluka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fefdws', to='store.taluka'),
            preserve_default=False,
        ),
    ]
