# Generated by Django 4.1.5 on 2023-03-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_station_taluka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='own_rate',
        ),
    ]
