# Generated by Django 4.1.5 on 2023-04-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_district_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eeredfed', to='store.office_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taluka',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ddfdf', to='store.office_location'),
            preserve_default=False,
        ),
    ]
