# Generated by Django 4.1.5 on 2023-04-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_station_office_location_taluka_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='onaccount',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsfwfe', to='store.office_location'),
            preserve_default=False,
        ),
    ]
