# Generated by Django 4.1.5 on 2023-04-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_consignor_office_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fefefe4gefd', to='store.office_location'),
            preserve_default=False,
        ),
    ]
