# Generated by Django 4.1.5 on 2023-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_expense',
            name='note',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
