# Generated by Django 4.1.5 on 2024-02-16 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_price_truck_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_expense',
            name='paid_on',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 3, 53, 30, 864532)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_paid_on',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 3, 53, 30, 863533)),
        ),
    ]
