# Generated by Django 4.1.5 on 2024-02-16 22:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_other_expense_paid_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_expense',
            name='paid_on',
        ),
        migrations.AddField(
            model_name='builty_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 24, 35, 604720)),
        ),
        migrations.AddField(
            model_name='builty_expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 24, 35, 605728)),
        ),
        migrations.AddField(
            model_name='salary',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 24, 35, 604720)),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 24, 35, 605728)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_paid_on',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 4, 24, 35, 605728)),
        ),
    ]
