# Generated by Django 4.1.5 on 2024-02-16 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_salary_date_alter_builty_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 25, 53, 841875)),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 25, 53, 843362)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_paid_on',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 4, 25, 53, 843362)),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 4, 25, 53, 841875)),
        ),
    ]
