# Generated by Django 4.1.5 on 2024-02-17 09:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_builty_expense_date_alter_other_expense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='expense_date',
        ),
        migrations.AddField(
            model_name='builty_expense',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty_expense',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='other_expense',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_expense',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 14, 50, 0, 891788)),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='builty_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 50, 0, 889790)),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 50, 0, 890788)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_paid_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 50, 0, 890788)),
        ),
    ]
