# Generated by Django 4.1.5 on 2024-02-17 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_salary_expense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builty_expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='other_expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='truck_expense',
            name='date',
        ),
        migrations.AddField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 59, 21, 733009)),
        ),
        migrations.AddField(
            model_name='other_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 59, 21, 734017)),
        ),
        migrations.AddField(
            model_name='salary',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 14, 59, 21, 735018)),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 59, 21, 734017)),
        ),
    ]
