# Generated by Django 4.1.5 on 2024-02-17 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='expense_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='builty_expense',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='expense_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_paid_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='expense_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
