# Generated by Django 4.1.5 on 2024-02-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0017_alter_builty_expense_user_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='employee',
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
