# Generated by Django 4.1.5 on 2024-03-04 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_ack_history_update_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0028_alter_bank_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfer_fund',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='diesel_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 42, 38, 890072, tzinfo=datetime.timezone.utc))),
                ('builty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdfgedfd', to='transactions.builty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
