# Generated by Django 4.1.5 on 2024-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_auto_20240307_1206'),
        ('expenses', '0037_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
    ]
