# Generated by Django 3.2.15 on 2024-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0038_merge_20240311_1950'),
        ('expenses', '0039_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
    ]
