# Generated by Django 4.1.5 on 2024-03-20 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_taluka_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0044_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_expense',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary_paid_on',
        ),
        migrations.RemoveField(
            model_name='transfer_fund',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='truck_expense',
            name='expense_date',
        ),
        migrations.AlterField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='diesel_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfer_fund',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='truck_diesel_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liter', models.FloatField()),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2024, 3, 20, 7, 37, 30, 400756, tzinfo=datetime.timezone.utc))),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdfgedfd', to='store.truck_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
