# Generated by Django 3.2.15 on 2024-03-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0040_merge_20240311_1957'),
        ('expenses', '0049_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
    ]
