# Generated by Django 3.2.15 on 2024-03-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0050_merge_20240320_1416'),
        ('expenses', '0052_remove_other_expense_payment_date_and_more'),
    ]

    operations = [
    ]
