# Generated by Django 4.1.5 on 2024-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0054_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty_expense',
            name='is_porch',
            field=models.BooleanField(default=False),
        ),
    ]
