# Generated by Django 3.2.15 on 2024-04-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0053_merge_20240322_2126'),
        ('expenses', '0054_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
    ]
