# Generated by Django 3.2.15 on 2024-04-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0055_builty_expense_is_porch'),
        ('expenses', '0055_merge_20240404_1916'),
    ]

    operations = [
    ]
