# Generated by Django 3.2.15 on 2024-04-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0056_alter_diesel_expense_entry_date_and_more'),
        ('expenses', '0056_merge_20240406_0138'),
    ]

    operations = [
    ]
