# Generated by Django 4.1.5 on 2024-04-11 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0061_alter_builty_expense_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
