# Generated by Django 3.2.15 on 2024-04-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0057_merge_20240409_1044'),
        ('expenses', '0063_alter_builty_expense_entry_date'),
    ]

    operations = [
    ]
