# Generated by Django 3.2.15 on 2024-04-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0065_alter_builty_expense_entry_date'),
        ('expenses', '0068_alter_builty_expense_entry_date'),
    ]

    operations = [
    ]
