# Generated by Django 3.2.15 on 2024-04-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0069_alter_builty_expense_entry_date_and_more'),
        ('expenses', '0069_merge_20240414_0336'),
    ]

    operations = [
    ]
