# Generated by Django 3.2.15 on 2024-04-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0070_alter_builty_expense_entry_date_and_more'),
        ('expenses', '0070_merge_20240414_1531'),
    ]

    operations = [
    ]
