# Generated by Django 3.2.15 on 2024-04-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0071_alter_builty_expense_entry_date_and_more'),
        ('expenses', '0071_merge_20240414_1648'),
    ]

    operations = [
    ]
