# Generated by Django 3.2.15 on 2024-04-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0072_alter_builty_expense_entry_date'),
        ('expenses', '0072_merge_20240414_1755'),
    ]

    operations = [
    ]
