# Generated by Django 3.2.15 on 2024-04-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0073_merge_20240414_1805'),
        ('expenses', '0075_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
    ]
