# Generated by Django 3.2.15 on 2024-04-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0078_merge_20240414_1829'),
        ('expenses', '0082_alter_fund_entry_date'),
    ]

    operations = [
    ]
