# Generated by Django 4.1.5 on 2024-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0083_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diesel_expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transfer_fund',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck_diesel_expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
