# Generated by Django 4.1.5 on 2024-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0084_alter_builty_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='closing_balance',
            name='closing_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diesel_expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer_fund',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truck_diesel_expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
