# Generated by Django 3.2.15 on 2024-04-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0083_merge_20240415_0310'),
        ('expenses', '0085_alter_builty_expense_amount_and_more'),
    ]

    operations = [
    ]
