# Generated by Django 3.2.15 on 2024-04-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0086_merge_20240420_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
