# Generated by Django 4.1.5 on 2023-04-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=50)),
                ('challan_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='builty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builty_no', models.CharField(max_length=50)),
                ('DC_date', models.DateField()),
                ('consignee', models.CharField(max_length=50)),
                ('bags', models.FloatField()),
                ('delivery_no', models.FloatField()),
                ('mobile_no', models.FloatField(blank=True, null=True)),
                ('ex_for', models.CharField(choices=[('for', 'for'), ('ex', 'ex')], default='for', max_length=50)),
                ('mode', models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('mt', models.FloatField(default=0.0)),
                ('freight', models.FloatField(default=0.0)),
                ('less_advance', models.FloatField(default=0.0)),
                ('less_tds', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.FloatField(default=0)),
                ('diesel', models.FloatField(default=0.0)),
                ('editable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel', models.FloatField(default=0.0)),
                ('note', models.CharField(max_length=50)),
                ('builty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_trip_is', to='transactions.builty')),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdfdcxcde', to='store.station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfdcxcfbgefwd', to='store.station')),
            ],
        ),
        migrations.CreateModel(
            name='request_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('builty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_request', to='transactions.builty')),
            ],
        ),
    ]
