# Generated by Django 4.1.5 on 2023-04-02 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_edit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='builty',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dffdcxvc', to='store.article'),
        ),
        migrations.AddField(
            model_name='builty',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwe', to='store.company'),
        ),
        migrations.AddField(
            model_name='builty',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wdsfgv', to='store.consignor'),
        ),
        migrations.AddField(
            model_name='builty',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sddcxfw', to='store.district'),
        ),
        migrations.AddField(
            model_name='builty',
            name='onaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfdfgfdgv', to='store.onaccount'),
        ),
        migrations.AddField(
            model_name='builty',
            name='petrol_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdsfgv', to='store.petrol_pump'),
        ),
        migrations.AddField(
            model_name='builty',
            name='station_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdssdsdsdcs', to='store.station'),
        ),
        migrations.AddField(
            model_name='builty',
            name='station_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvccxcred', to='store.station'),
        ),
        migrations.AddField(
            model_name='builty',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdscsc', to='store.taluka'),
        ),
        migrations.AddField(
            model_name='builty',
            name='truck_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsc', to='store.truck_details'),
        ),
        migrations.AddField(
            model_name='builty',
            name='truck_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cxcdfdfvd', to='store.truck_owner'),
        ),
        migrations.AddField(
            model_name='builty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ack',
            name='builty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_ack', to='transactions.builty'),
        ),
    ]
