# Generated by Django 4.1.5 on 2023-04-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_driver_office_location_petrol_pump_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack',
            name='builty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='have_ack', to='transactions.builty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ack',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dffdcxvc', to='store.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdwe', to='store.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='consignor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wdsfgv', to='store.consignor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sddcxfw', to='store.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='mobile_no',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='onaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wfdfgfdgv', to='store.onaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='petrol_pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdsfgv', to='store.petrol_pump'),
        ),
        migrations.AddField(
            model_name='builty',
            name='station_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdssdsdsdcs', to='store.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='station_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dvccxcred', to='store.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='taluka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdscsc', to='store.taluka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='truck_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsc', to='store.truck_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='truck_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cxcdfdfvd', to='store.truck_owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_edit',
            name='history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request_edit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builty',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='freight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_tds',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mode',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
