# Generated by Django 4.1.5 on 2023-03-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_petrol_pump'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty',
            name='petrol_pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wdsfgv', to='store.petrol_pump'),
            preserve_default=False,
        ),
    ]
