# Generated by Django 4.1.5 on 2023-04-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_builty_bags1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builty',
            name='bags1',
        ),
    ]
