# Generated by Django 4.1.5 on 2023-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_builty_petrol_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_edit',
            name='history',
            field=models.BooleanField(default=False),
        ),
    ]
