# Generated by Django 4.1.5 on 2023-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_request_edit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
