# Generated by Django 4.1.5 on 2023-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_builty_bags1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='bags',
            field=models.IntegerField(),
        ),
    ]
