# Generated by Django 4.1.5 on 2023-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_builty_challan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builty',
            name='challan_date',
        ),
        migrations.AddField(
            model_name='ack',
            name='challan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
