# Generated by Django 4.1.5 on 2023-04-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_from_station'),
        ('transactions', '0006_alter_sub_trip_station_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_trip',
            name='station_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdfdcxcde', to='store.station'),
        ),
    ]
