# Generated by Django 4.1.5 on 2023-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_builty_less_tds_alter_builty_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mode',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
