# Generated by Django 4.1.5 on 2023-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_builty_freight_alter_builty_less_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
