# Generated by Django 4.1.5 on 2023-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_builty_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='freight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_tds',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
