# Generated by Django 4.1.5 on 2023-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_delete_sub_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='delivery_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
