# Generated by Django 4.1.5 on 2023-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_builty_balance_alter_builty_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(max_length=50),
        ),
    ]
