# Generated by Django 4.1.5 on 2023-04-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_driver_driving_licence_expiry_date'),
        ('transactions', '0011_alter_builty_delivery_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='station_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdssdsdsdcs', to='store.from_station'),
        ),
    ]
