# Generated by Django 4.1.5 on 2023-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_builty_builty_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty',
            name='mobile_no',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
