# Generated by Django 4.1.5 on 2023-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_builty_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
