# Generated by Django 4.1.5 on 2023-04-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_builty_station_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='DC_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
