# Generated by Django 4.1.5 on 2024-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_builty_dc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='builty',
            name='voucher_payment_bank_ac_ifsc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='voucher_payment_bank_ac_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='builty',
            name='voucher_payment_mode',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='builty',
            name='voucher_payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
