# Generated by Django 4.1.5 on 2023-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_builty_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mobile_no',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
