# Generated by Django 4.1.5 on 2024-03-03 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_ack_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_history',
            old_name='challan_date',
            new_name='challan_date_before',
        ),
        migrations.RenameField(
            model_name='ack_history',
            old_name='challan_number',
            new_name='challan_number_before',
        ),
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 22, 58, 697778, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
