# Generated by Django 4.1.5 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_builty_balance_alter_builty_less_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='freight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='less_tds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='builty',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
