# Generated by Django 4.1.5 on 2024-03-03 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_rename_challan_date_ack_history_challan_date_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 44, 7, 304089, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
