# Generated by Django 4.1.5 on 2023-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_builty_balance_alter_builty_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='less_advance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
