# Generated by Django 4.1.5 on 2023-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_builty_less_advance_alter_builty_less_tds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
