# Generated by Django 4.1.5 on 2024-03-04 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_ack_history_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 4, 4, 52, 35, 376076, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='voucher_payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50, null=True),
        ),
    ]
