# Generated by Django 4.1.5 on 2024-03-07 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_ack_history_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 7, 6, 31, 3, 37136, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
