<<<<<<< HEAD
# Generated by Django 3.2.15 on 2024-03-07 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
=======
# Generated by Django 4.1.5 on 2024-03-10 10:02

import datetime
from django.db import migrations, models
>>>>>>> 2f80f6fd8f87460aee3f2b34be155a66d0871093


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_ack_history_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
<<<<<<< HEAD
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 7, 6, 36, 7, 368458, tzinfo=utc), null=True),
=======
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 10, 10, 2, 19, 238979, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 2f80f6fd8f87460aee3f2b34be155a66d0871093
        ),
    ]
