# Generated by Django 4.1.5 on 2024-03-20 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_alter_ack_history_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 20, 7, 37, 30, 385299, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
