# Generated by Django 4.1.5 on 2024-04-05 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_alter_ack_history_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 5, 17, 56, 46, 732739, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='voucher_payment_bank_ac_ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='voucher_payment_bank_ac_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
