# Generated by Django 4.1.5 on 2024-04-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_alter_ack_history_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 5, 18, 3, 54, 501846, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
