# Generated by Django 4.1.5 on 2024-04-11 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0060_remove_builty_voucher_payment_bank_ac_ifsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 11, 15, 35, 6, 326820, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
